FROM node:18-alpine
WORKDIR /app
COPY package.json package-lock.json ./
RUN echo "Conteúdo de /app:" && ls -la /app && echo "Conteúdo de package.json:" && cat package.json || true
RUN if [ -f package-lock.json ]; then npm ci --omit=dev; else npm install --omit=dev; fi
